### ISSUE TITLE
Unable to connect to Play Store to check for updates

### ISSUE THREAD

**Issue by ShravanJ** [edsnider/latestversionplugin#11]
If this issue is for a new feature, please skip the "Bug" section and fill out the "Feature Request" section at the bottom.

## Bug

Plugin Version:  1.1.2
Platform (e.g., Android v21):  Android API 26 (8.0.0)
Device/Hardware:  Samsung Galaxy S9 SM-G960U1

### Expected behavior
App should be able to connect to Google Play to see if there is a newer version of the app available and prompt the user to download the latest version

### Actual behavior
App update check fails and an exception is raised

### Steps to reproduce the issue
- Call CrossLatestVersion.Current.IsUsingLatestVersion() in a try-catch
- The following exception is caught:
Plugin.LatestVersion.LatestVersionException: Error comparing current app version number with latest. Version name=1.0.8 and lastest version= . ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

**Comment by edsnider** [comment]
It's throwing an `HTTPRequestException` which is always a possibility when making web requests so it's good that you're wrapping in a try/catch.  Can you confirm you are connected to the internet and that the app is listed in the Play Store? Can you share the app id (e.g., `com.example.myapp`)?

**Comment by ShravanJ** [comment]
Yes, I am able to reach the Play Store listing on the device. The app ID is com.orchr.MyORCHR.

**Comment by edsnider** [comment]
I'm getting back a response for `com.orchr.MyORCHR` with the plugin. 
`await GetLatestVersionNumber("com.orchr.MyORCHR")` (which `IsUsingLatestVersion()` calls) return `1.0.7`.

**Comment by ShravanJ** [comment]
I'm suspecting it might be related to our http client setup. We are using modernhttpclient along with the AndroidClientHandler and Native TLS 1.2+ selected. Have you tried this combination out with the plugin?

**Comment by edsnider** [comment]
No, I have not. The plugin itself is using `System.Net.HttpClient`.

**Comment by ShravanJ** [comment]
I have finally found the root cause of the issue. The HTTP call was failing because we are using moddernhttpclient coupled with the AndroidClientHandler to implement SSL certificate pinning. I confirmed this by writing a small app to test out the functionality of the plugin alone and it worked fine as expected. Then, I added in modernhttpclient and the SSL certificate validation callback code and the plugin immediately stopped working. To solve this, I added in the public key of play.google.com to my list of hardcoded public keys in the app. After adding this, the plugin is working as intended. Interestingly enough I never had to add in the public key for itunes.apple.com for the update check to work on iOS. Seems like its some quirk with the AndroidClientHandler implementation. 

You can mark this issue as resolved. Thanks.
