### ISSUE TITLE
Hello!  Could a method exist that automatically installs the new version?

### ISSUE THREAD

**Issue by josediegopassos** [edsnider/latestversionplugin#17]
Hello!

Could a method exist that automatically installs the new version?

**Comment by TheSayvior** [comment]
No, thats would be a security breach, you can only make it impossible to enter the app if the current app isent the newest version.

Android - has a setting that allows this, users can active it and all their apps will automatically update during the night if connected to power and wifi.
iOS - dosent allow it, users must make the choice to updare.
