### ISSUE TITLE
Error comparing current app version number with latest

### ISSUE THREAD

**Issue by xphacter** [edsnider/latestversionplugin#19]
## Bug
Exception Unhandled. If the phone has no internet connection the app will crash trying to compare versions.

Plugin Version:  1.1.2
Platform (e.g., Android v21):  
Device/Hardware:  iPhone X

### Actual behavior
Unhandled Exception:

Plugin.LatestVersion.LatestVersionException: Error comparing current app version number with latest. Bundle version=1.0 and lastest version= . occurred

### Steps to reproduce the issue
Put device into Airplane Mode
- 
- 

## Feature Request

Description:

**Comment by DottorPagliaccius** [comment]
same here

**Comment by edsnider** [comment]
This plugin relies on connectivity to the iTunes API (or Play Store or Microsoft Store) to get the app's latest release version number. The plugin will throw a `LatestVersionException` if an exception occurs when comparing the installed version with the latest version, or if an exception occurs when trying to contact the App Store. Your code should catch and handle this exception accordingly.
