### ISSUE TITLE
IsUsingLatestVersion throwing exception in development

### ISSUE THREAD

**Issue by Im-PJ** [edsnider/LatestVersionPlugin#4]
My app is in development and it is not yet available in andrid playstore. 
IsUsingLatestVersion() is throwing below exception. Is this expected?

Plugin.LatestVersion.LatestVersionException: Error comparing current app version number with latest. Version name=0.1 and lastest version= . ---> Plugin.LatestVersion.LatestVersionException: Error connecting to the Play Store. Url=https://play.google.com/store/apps/details?id=com.company.employee

**Comment by edsnider** [comment]
Yes, that is expected based on the current implementation. If it is not already in the Play Store there will be no version to compare to, and in this case there is no store listing for `com.company.employee` and therefore it is getting a `404` HTTP status code.

**Comment by pierrebrito** [comment]
Do I need to do any other configuration?

Because even with the App published in the Play Store, Exception continues to happen.

**Comment by edsnider** [comment]
@pierrebrito what is the app id in the Play Store?

**Comment by pierrebrito** [comment]
@edsnider this is link: https://play.google.com/store/apps/details?id=siamac.apps.teste.PetsSPets

**Comment by edsnider** [comment]
Looks like there have been some changes to the play.google.com HTML. Will create a new issue as this is a separate issue from the original question on this issue.

**Comment by nmano2188** [comment]
Any workaround?
