### ISSUE TITLE
Change version number place in AF_initDataCallback

### ISSUE THREAD

**Issue by elteka** [edsnider/latestversionplugin#47]
## Bug

Plugin Version:  master
Platform (e.g., Android v21):  Android
Device/Hardware:  Android

### Expected behavior
Class LatestVersion.android.cs
Method GetLatestVersionNumber() retrieve the last version in Play Store

### Actual behavior
Class LatestVersion.android.cs
Method GetLatestVersionNumber() can't convert javascript unexpected value to object and throw Exception

### Steps to reproduce the issue
- CrossLatestVersion.Current.IsUsingLatestVersion();
or
- CrossLatestVersion.Current.GetLatestVersionNumber();
 

## Feature Request

Description:  I solve this bug changing GetLatestVersionNumber() method, line 81, changing key: 'ds:4' for key: 'ds:5'

original line
 var scripts = doc.DocumentNode.Descendants()
                     .Where(n => n.Name == "script" && n.InnerText.Contains("AF_initDataCallback({key: 'ds:4'"))
                     .ToArray();

changed line
 var scripts = doc.DocumentNode.Descendants()
                     .Where(n => n.Name == "script" && n.InnerText.Contains("AF_initDataCallback({key: 'ds:5'"))
                     .ToArray();

**Comment by wtheronjones** [comment]
This ticket duplicates Issue # 42, which does actually have a fix checked in for it.
The nuget package hasn't been updated yet though...

**Comment by marcelovargas** [comment]
The version 2.1.1-beta has parsing error.

**Comment by Auto72** [comment]
I can confirm the FIX reported at the top of this article, under "Feature Request", DOES work !!!

var scripts = doc.DocumentNode.Descendants()
.Where(n => n.Name == "script" && n.InnerText.Contains("AF_initDataCallback({key: 'ds:5'"))
.ToArray();

Can someone make a new version of the NuGet package, please?
