### ISSUE TITLE
Android implementation is broken due to changes in play.google.com

### ISSUE THREAD

**Issue by edsnider** [edsnider/LatestVersionPlugin#5]
The HTML in play.google.com has changed which breaks the pattern matching in the Android implementation. As a result `GetLatestVersionNumber()` returns a blank string and `IsUsingLatestVersion()` throws a `LatestVersionException`.

Discovered in #4

**Comment by pierrebrito** [comment]
Thanks for correcting the bug!

**Comment by edsnider** [comment]
@pierrebrito not in nuget yet - build packaging is failing for some reason in AppVeyor. I may just create the nuget manually in the meantime. Sorry for the delay - automated CI/CD is awesome until it fails :-/

**Comment by edsnider** [comment]
@kikolopes90 thank you I will adjust accordingly.

**Comment by edsnider** [comment]
@pierrebrito @kikolopes90 beta NuGet package with fix is available for testing - https://www.nuget.org/packages/Xam.Plugin.LatestVersion/1.1.1-beta60

**Comment by pierrebrito** [comment]
@edsnider Thank you! I was anxiously waiting for this

**Comment by edsnider** [comment]
Fixed in 1.1.1
