### ISSUE TITLE
iOS: OpenAppInStore() does not work

### ISSUE THREAD

**Issue by simader** [edsnider/latestversionplugin#6]
## Bug
When I call await CrossLatestVersion.Current.OpenAppInStore(); on my Iphone SE it opens the store but it says "Cannot connct to App Store"

Plugin Version:  newest
Platform (e.g., Android v21):  
Device/Hardware:  IPhone SE

### Expected behavior
navigates to the app.

**Comment by simader** [comment]
There was no reaction so far. Still the same behaviour

**Comment by nmano2188** [comment]
Same issue..

**Comment by edsnider** [comment]
I looked into this issue and it worked for me.  However, I did notice some inconsistencies  with the URL the library uses to open the app in the App Store depending on the specific app, app name and version of iOS. 
Which version of iOS are you all seeing this issue on?

**Comment by pfbwitz** [comment]
> I looked into this issue and it worked for me. However, I did notice some inconsistencies with the URL the library uses to open the app in the App Store depending on the specific app, app name and version of iOS.
> Which version of iOS are you all seeing this issue on?

12.0 (16A366))

**Comment by simader** [comment]
I experienced some strange behavior if the CFBundleIdentifier contains some special characters like a dot. 
I changed our CFBundleName to a Name without dot and then at least it is found in the search.

**Comment by vinicius-stutz** [comment]
Hi! I get the error message: "Error parsing content from the App Store" when call `await CrossLatestVersion.Current.IsUsingLatestVersion();`

**Comment by kainaalmeida** [comment]
I looked into this issue and it worked for me. However, I did notice some inconsistencies with the URL the library uses to open the app in the App Store depending on the specific app, app name and version of iOS.
Which version of iOS are you all seeing this issue on?

Iphone SE 12.0

**Comment by kainaalmeida** [comment]
> 
> 
> I looked into this issue and it worked for me. However, I did notice some inconsistencies with the URL the library uses to open the app in the App Store depending on the specific app, app name and version of iOS.
> Which version of iOS are you all seeing this issue on?

iPhone SE 12.0

**Comment by AnthonyLatty** [comment]
This seems to still be a valid issue, are there any work arounds??

**Comment by prash6001** [comment]
Not yet fixed? Any solution on this?

**Comment by TheSayvior** [comment]
The problem arises in the iOS when the URL is created
UIKit.UIApplication.SharedApplication.OpenUrl(new NSUrl($"http://appstore.com/{appName}"));

the url needs to be exstended with the ID of the app

UIKit.UIApplication.SharedApplication.OpenUrl(new NSUrl($"http://appstore.com/{appName}/id{AppId}")); then it should work this is based on the fact that I have to add the ID when using 
Xamarin.Essencials.Launcher.openAsync(new Uri("https://apps.apple.com/dk/app/{AppName}/id{AppId}"));

**Comment by TheSayvior** [comment]
I got the t UIKit.UIApplication.SharedApplication.OpenUrl method to work. It must be updated with the new path such that 
`http://appstore.com/{appName}` 
is replaced with 
`https://apps.apple.com/dk/app/{AppName}/id{AppId}`

Additionally the code dosent take into acount none english characters so the,  `MakeSafeForAppStoreShortLinkUrl(string value)` must be updated, in my case my app name has a "ø" which isent allowed.
therefore update the method with:
`             private string MakeSafeForAppStoreShortLinkUrl(string value) 
                        {
                        ...
                        var safeValue = regex.Replace(value, string.Empty);

                        safeValue = safeValue.Replace(" ", string.Empty)
                                 .Replace("&", "and")
                                 .Replace("å", "a")
                                 .Replace("ø", "o")
                                 .Replace("æ", "ae")
                                 .ToLower();

            return safeValue;
        }
`

**Comment by TheSayvior** [comment]
Another way of doing it would be to create a copy of the `GetLatestVersionNumber` as a private method and calling it `GetAppStoreUrl` you should then replace the return property ["version"] with ["trackViewUrl"] and you can then use the result of that in your app store request 
`string storeUrl = await GetAppStoreUrl(BundleIdentifier);
 UIKit.UIApplication.SharedApplication.OpenUrl(new NSUrl(storeUrl));`

**Comment by edsnider** [comment]
Fix is available in latest nuget beta - https://www.nuget.org/packages/Xam.Plugin.LatestVersion/2.0.0-beta.76

**Comment by grounch** [comment]
The fix in 2.0.0 beta doesn't work for me, for iOS i get "Safari cannot open the page because the address is invalid" and it crashes in Android.
