### ISSUE TITLE
Supported Android version number shown as 10.0+

### ISSUE THREAD

**Issue by johnshardman** [edsnider/latestversionplugin#7]
If this issue is for a new feature, please skip the "Bug" section and fill out the "Feature Request" section at the bottom.

## Bug
At date of reading (26th September 2018), the documentation at https://github.com/edsnider/latestversionplugin#supported-platforms-and-versions shows
"Xamarin.Android | Yes | 10.0+"

That 10.0+ is presumably incorrect.

### Expected behavior

A version number that is correct.

### Actual behavior

Android version number shown as 10.0+

### Steps to reproduce the issue

Read https://github.com/edsnider/latestversionplugin#supported-platforms-and-versions

**Comment by edsnider** [comment]
Can you explain why you think 10.0+ is incorrect?
